### ISSUE TITLE
pa.py程序报错

### ISSUE THREAD

**Issue by Clancy6** [No5972/pixiv-github-action#4]
作者你好，首先非常感谢您提供的开源程序，只是我[参考您的程序并部署](https://github.com/Clancy6/PixivDailyPull/tree/runner)一个月后报错：
```
Run python pa.py
Traceback (most recent call last):
  File "/home/runner/work/PixivDailyPull/PixivDailyPull/pa.py", line 58, in <module>
Downloading the picture 1    response:
 <Response [200]>
    getAllPicUrl()
  File "/home/runner/work/PixivDailyPull/PixivDailyPull/pa.py", line 53, in getAllPicUrl
    print('OK' if getSinglePic(url) else "FAILED", end='\n')
                  ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/PixivDailyPull/PixivDailyPull/pa.py", line 3[7](https://github.com/Clancy6/PixivDailyPull/actions/runs/3805230454/jobs/6473021399#step:6:8), in getSinglePic
    pic = requests.get(picture.group(1), headers=headers)
                       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
Error: Process completed with exit code 1.
```
**[详细日志](https://pipelines.actions.githubusercontent.com/serviceHosts/fa3ba480-398f-4414-a7c7-b28c820870ce/_apis/pipelines/1/runs/65/signedlogcontent/2?urlExpires=2022-12-30T06%3A35%3A28.4466442Z&urlSigningMethod=HMACV1&urlSignature=SvWf%2BoVnttKxihNMpIayTC%2FwRkm%2BS8ztwg2aAiZGuVE%3D)**
请问是Pixiv屏蔽GitHub workflow服务器ip了吗？感谢

**Comment by No5972** [comment]
It seems that some pictures of this got a sanity level that is a bit high, which mean that this picture contains inappropriate content. This caused the picture URL unable to load. The only thing we can do is to skip this picture. This indicator is automatically calculated by the platform through an AI technology.

Modify [this line in ```pa.py```](https://github.com/Clancy6/PixivDailyPull/blob/runner/pa.py#L20)

```python
if re.search('"xRestrict":(.+?),"sl"', response.text).group() != '"xRestrict":0,"sl"':
```

to 

```python
if re.search('"xRestrict":(.+?),"sl"', response.text).group() != '"xRestrict":0,"sl"' or re.search('"original":(.+?),', response.text).group() == '"original":null},':
```

in order to fixed this.
